services:
  palladio-approximator:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true  # Keep stdin open
    tty: true         # Allocate a pseudo-TTY
