version: '3.8'

services:
  palladio:
    build:
      context: .
      dockerfile: Dockerfile
    image: palladio_approximator
    container_name: palladio_approximator
    volumes:
      - .:/app
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
